AppBundle\Entity\Program:
    type: entity
    table: program
    indexes:
        movie_id:
            columns:
                - movie_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        datetime:
            type: datetime
            nullable: false
        finish:
            type: datetime
            nullable: false
    manyToOne:
        movie:
            targetEntity: Movie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                movie_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
